name: Build ProxyReset Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    if: startsWith(github.event.head_commit.message, 'v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install rsrc (for icon)
        run: go install github.com/akavel/rsrc@latest

      - name: Prepare the icon
        run: |
          # Remove the leading 'v' from the commit message using PowerShell
          $VERSION = "${{ github.event.head_commit.message }}" -replace '^v', ''

          # Use rsrc to embed the icon directly (without manifest)
          rsrc -ico=icon.ico -o rsrc.syso

      - name: Build and zip (ia32)
        run: |
          $env:GOARCH="386"
          $env:GOOS="windows"
          go build -ldflags="-H windowsgui" -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxy-reset-ia32.zip
          Rename-Item proxy-reset.exe proxy-reset-ia32.exe

      - name: Build and zip (x64)
        run: |
          $env:GOARCH="amd64"
          $env:GOOS="windows"
          go build -ldflags="-H windowsgui" -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxy-reset-x64.zip
          Rename-Item proxy-reset.exe proxy-reset-x64.exe

      - name: Build and zip (arm64)
        run: |
          $env:GOARCH="arm64"
          $env:GOOS="windows"
          go build -ldflags="-H windowsgui" -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxy-reset-arm64.zip
          Rename-Item proxy-reset.exe proxy-reset-arm64.exe

      - name: Upload to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            proxy-reset-ia32.exe
            proxy-reset-ia32.zip
            proxy-reset-x64.exe
            proxy-reset-x64.zip
            proxy-reset-arm64.exe
            proxy-reset-arm64.zip
          tag: '${{ github.event.head_commit.message }}'
          draft: true
