name: Build ProxyReset Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    if: startsWith(github.event.head_commit.message, 'v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build and zip (ia32)
        run: |
          $env:GOARCH="386"
          $env:GOOS="windows"
          go build -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxyReset-ia32.zip
          Rename-Item proxy-reset.exe proxyReset-ia32.exe

      - name: Build and zip (x64)
        run: |
          $env:GOARCH="amd64"
          $env:GOOS="windows"
          go build -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxyReset-x64.zip
          Rename-Item proxy-reset.exe proxyReset-x64.exe

      - name: Build and zip (arm64)
        run: |
          $env:GOARCH="arm64"
          $env:GOOS="windows"
          go build -o proxy-reset.exe proxyReset.go
          Compress-Archive -Path proxy-reset.exe -DestinationPath proxyReset-arm64.zip
          Rename-Item proxy-reset.exe proxyReset-arm64.exe

      - name: Upload to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            proxyReset-ia32.exe
            proxyReset-ia32.zip
            proxyReset-x64.exe
            proxyReset-x64.zip
            proxyReset-arm64.exe
            proxyReset-arm64.zip
          tag: '${{ github.event.head_commit.message }}'
