name: Build ProxyReset Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build proxy reset executable (ia32)
        run: |
          $env:GOARCH="386"
          $env:GOOS="windows"
          go build -o proxyReset-ia32.exe proxyreset.go

      - name: Build proxy reset executable (x64)
        run: |
          $env:GOARCH="amd64"
          $env:GOOS="windows"
          go build -o proxyReset-x64.exe proxyreset.go

      - name: Build proxy reset executable (arm64)
        run: |
          $env:GOARCH="arm64"
          $env:GOOS="windows"
          go build -o proxyReset-arm64.exe proxyreset.go

      - name: Upload to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            proxyReset-ia32.exe
            proxyReset-x64.exe
            proxyReset-arm64.exe
          tag: '${{ github.event.head_commit.message }}'
